[workspace]
members = [
    "circuits",
    "client",
    "core",
    "executor",
    "plonky2/plonky2",
    "plonky2/field",
]

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true