[package]
name = "olavm-circuits"
version = "0.1.0"
description = "Olavm core components"
readme = "README.md"
license = "MIT"
edition = "2021"

[lib]
bench = false
doctest = false

[dependencies]
vm-core = { package = "olavm-core", path = "../vm-core", version = "0.1.0", default-features = false }